# -*- coding: utf-8 -*-
"""Syntecxhub_command_line_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105OGEKzjAsGYgbrfmuImBqnXJpyCJXBF
"""

# ─────────────────────────────────────────────
#  command_line_calculator.py
#  A beginner-friendly command-line calculator
# ─────────────────────────────────────────────


# ── CALCULATION FUNCTIONS ──────────────────────

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error: Cannot divide by zero."
    return a / b


# ── INPUT HELPERS ──────────────────────────────

def get_number(prompt):
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("  Invalid input. Please enter a number.\n")

def get_operator():
    valid_operators = ['+', '-', '*', '/']
    while True:
        op = input("  Enter operator (+  -  *  /): ").strip()
        if op in valid_operators:
            return op
        print("  Invalid operator. Choose from +  -  *  /\n")


# ── CALCULATION RUNNER ─────────────────────────

def calculate(a, operator, b):
    if operator == '+':
        return add(a, b)
    elif operator == '-':
        return subtract(a, b)
    elif operator == '*':
        return multiply(a, b)
    elif operator == '/':
        return divide(a, b)


# ── DISPLAY HELPERS ────────────────────────────

def show_menu():
    print("\n" + "─" * 35)
    print("       COMMAND-LINE CALCULATOR")
    print("─" * 35)
    print("  Operations: +   -   *   /")
    print("  Type 'exit' at any prompt to quit.")
    print("─" * 35)

def show_result(a, operator, b, result):
    print(f"\n  ➤  {a} {operator} {b} = {result}\n")


# ── MAIN PROGRAM LOOP ──────────────────────────

def main():
    show_menu()

    while True:
        print("\n  [ New Calculation ]")

        # Step 1: Get first number
        a = get_number("  Enter first number  : ")

        # Step 2: Get operator
        operator = get_operator()

        # Step 3: Get second number
        b = get_number("  Enter second number : ")

        # Step 4: Calculate and show result
        result = calculate(a, operator, b)
        show_result(a, operator, b, result)

        # Step 5: Ask to continue or exit
        again = input("  Calculate again? (yes / no): ").strip().lower()
        if again != 'yes':
            print("\n  Goodbye! Calculator closed.\n")
            break


# ── ENTRY POINT ────────────────────────────────

if __name__ == "__main__":
    main()